OBJECTS = find.out count.out accumulate.out roster.out fill.out \
		  fill_n.out copy.out elim_dumps.out biggies.out lambda.out \
		  transform.out bind.out check_size.out big_endian.out \
		  inserter.out unique_copy.out stream.out exp1029.out \
		  exp1030.out exp1031.out bookstore.out exp1033.out \
		  exp1034.out exp1035.out exp1036.out exp1037.out \
		  comma.out



include ../GNU_makefile_template

bookstore.out: Sales_item.h
