OBJECTS = wordcount.out set.out map.out  pair.out exp1117.out wordcount2.out \
		  exp1122.out authors.out transform.out my_transform.out \
		  my_wordcount.out


LOCFLAGS = -I../chapter-10

include ../GNU_makefile_template

