OBJECTS = fact.out static.out find_char.out compare.out print.out main.out \
		  sum.out leftvalue.out arrayref.out assert.out func.out \
		  func_pointer.out

LOCFLAGS = -D NDEBUG

include ../GNU_makefile_template
