OBJECTS = add_item.out add_item2.out add_items.out read_sales_item.out bookstore.out

include ../GNU_makefile_template

add_item.out add_item2.out add_items.out read_sales_item.out bookstore.out: Sales_item.h
