OBJECTS = string.out joinline.out countline.out join.out forrange.out \
		  toupper.out test.out hex.out depunct.out vector.out count_score.out \
		  uppercase.out exp3_20.out iterator.out exp3_23.out bin_search.out \
		  array.out exp3_36.out cstring.out exp3_41.out two_range_array.out

include ../GNU_makefile_template
